     
server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/users/**
        - id: account-service
          uri: http://localhost:8011
          predicates:
            - Path=/api/account/**

  application:
    name: gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka