
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cheikhdiouf/config-server-repo
          default-label: master
          clone-on-start: true

  application:
    name: config-service


