server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cheikhdiouf/config-server-repo.git
  application:
    name: config-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


